name: CI
on: [push, pull_request]
jobs:
  backend-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -U pip && pip install -r requirements.txt
      - run: python -c "import fastapi,uvicorn; print('backend deps ok')"
