name: Deploy Web

on:
  push:
    branches: [ "main" ]
    paths:
      - "web/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install & Build (Next.js)
        working-directory: web
        run: |
          npm ci || npm i
          npm run build

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Rsync .next & public & config
        run: |
          RSYNC_RSH="ssh -i key.pem -p ${{ secrets.SSH_PORT || 22 }} -o StrictHostKeyChecking=no"
          rsync -az --delete \
            web/.next web/public web/package.json web/next.config.mjs \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_DIR }}/web/

      - name: Restart web service
        run: |
          ssh -i key.pem -p ${{ secrets.SSH_PORT || 22 }} -o StrictHostKeyChecking=no \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "sudo systemctl restart skriptonika-web && sudo systemctl status skriptonika-web --no-pager -l"
